name: Run Selenium Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17" # or 11, depending on your project

      - name: Install Chrome
        run: |
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Set up ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP "\d+\.\d+\.\d+\.\d+" | cut -d '.' -f 1)
          wget -q https://chromedriver.storage.googleapis.com/${CHROME_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Build and run tests
        run: mvn -B test --file hamzat_ma_testing/pom.xml

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: hamzat_ma_testing/target/surefire-reports/

      - name: Print test summary
        if: always()
        run: |
          echo "\n===== TEST SUMMARY ====="
          if [ -f hamzat_ma_testing/target/surefire-reports/TEST-com.snbat.SideBarCategoryTest.xml ]; then
            cat hamzat_ma_testing/target/surefire-reports/TEST-*.xml
          else
            echo "No test summary XML files found."
          fi
